### ISSUE TITLE
How to recreate Couchbase from Postgres if needed

### ISSUE THREAD

**Issue by deepaktina** [hagnat/distributed-studies#3]
This may not be a very probably scenario but in case if needed how do we recreate couchbase from Postgres?

**Comment by hagnat** [comment]
There are several ways to store the pgsql data in cb. 

The easiest way is to make every entities [JsonSerializable](http://php.net/manual/en/class.jsonserializable.php). Once you hydrate an entity from the database, you will instantly place a json copy of it in the couchbase server. Next time you have fetch that same entity, it will be stored in the CB server, ready for use.

**Comment by hagnat** [comment]
The main idea is to make database and couchbase queries as services that can be stacked in a chain-of-responsability pattern. Once you find the information in one of the layers of the chain, you will propagate that information to the previous ones for future use.

**Comment by hagnat** [comment]
Another nifty way to replicate the structure from your pgsql server onto your cb server is: don't. You don't have to store information in CB in the same fashion as you do in your pgsql server. 

For one, data stored in those databases are different in nature: since you don't have relational entities in CB, you are not supposed to store the Product and the ProductCategory in different documents, but rather stored them in a single entity.

And another, you can add better contextualization of your information with the way you defined it in you json document. By using a well defined schema, such as [schema.org](http://schema.org), you can evaluate your information in a far better way than a pgsql row would ever be able to.
