### ISSUE TITLE
How do we structure RabbitMQ for writes to Postgres

### ISSUE THREAD

**Issue by deepaktina** [hagnat/distributed-studies#5]
In proposed architecture, are you envisioning RabbitMQ use solely as simple Produce/Consume based flow or different queues/exchanges for different kind of data? if this is simple produce/consume case - then would Kafka would be better choice?

**Comment by hagnat** [comment]
I proposed the use of RabbitMQ because it was the one i had more experience with, but any queueing system will do the trick. The proposed architecture is mostly produce/consume, so i don't see any reason for me to change to anything more robust than that beyond the opportunity of studying that technology
